name: Sciraider
on:
  schedule:
    - cron: '0 18 * * FRI'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - id: sciraider
        run: python -m sciraider.cli --cfg config/targets.yaml
      - name: Send Email
        if: steps.sciraider.outputs.sent == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "[Sciraider] ${{ steps.sciraider.outputs.range }} Digest"
          html_body: file://output/digest.html
